# Use an official Node image as the base image for running the Vue frontend in development mode
FROM node:latest

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy remaining source code to the working directory
COPY . .

# Expose the port on which the Vue development server will run
EXPOSE 5173

# Command to run the Vue development server
CMD ["npm", "run", "dev"]
