# Use an official Node image as the base image
FROM node:latest

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy remaining source code to the working directory
COPY . .

# Expose the port on which the Express.js server will run
EXPOSE 3000

# Command to run the Express server
CMD ["npm", "start"]
